autoDetectedPackages:
- cn.geekslife
- com.example.command
- com.example.flyweight
- com.example.interpreter
- com.example.iterator
- com.example.mediator
- com.example.memento
- com.example.proxy
- com.example.redis
- com.redis.bloomfilter
- observer
- state
- strategy
- template
enableAutoDetect: true
entryDisplayConfig:
  excludedPathPatterns: []
  skipJsCss: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: false
  skipNonProjectPackages: false
  skipPrivateMethods: false
  skipSetters: false
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: all
sourceDisplayConfig:
  color: blue
startOnDebug: false
